name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1
      - name: Download ShiftLeft CLI
        run: |
          curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl
  
      - name: Run sl analyze 1
        shell: bash
        run: |
          ./sl analyze --verbose --app "${GITHUB_REPOSITORY_OWNER}_${GITHUB_REPOSITORY#*/}" .
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
